#
#    ░░░░░██╗░█████╗░██████╗░███████╗██████╗░░█████╗░██╗░░██╗░█████╗░████████╗
#    ░░░░░██║██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██║░░██║██╔══██╗╚══██╔══╝
#    ░░░░░██║███████║██║░░██║█████╗░░██║░░██║██║░░╚═╝███████║███████║░░░██║░░░
#    ██╗░░██║██╔══██║██║░░██║██╔══╝░░██║░░██║██║░░██╗██╔══██║██╔══██║░░░██║░░░
#    ╚█████╔╝██║░░██║██████╔╝███████╗██████╔╝╚█████╔╝██║░░██║██║░░██║░░░██║░░░
#    ░╚════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░
#
#                    Version ${project.version}
#

# Sets the name of the server. Used in logging chat.
server: "server"

# Connects to the MySQL Database
MySQL:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  useSSL: true

JoinMessage:
  override: false
  message: "<green>%player_name% joined the game."

QuitMessage:
  override: false
  message: "<red>%player_name% left the game."


PrivateMessages:
  SenderMessage:
    segments:
      players: "<green>(<white>You <green>:arrow: <white><receiver><green>) "
      message: "<message>"
  ReceiverMessage:
    segments:
      players: "<green>(<white><sender> <green>:arrow: <white>You<green>) "
      message: "<message>"
    sounds:
      - BLOCK_NOTE_BLOCK_BELL
  SpyMessage:
    segments:
      players: "<green>(<white><sender> <green>:arrow: <white><receiver><green>) "
      message: "<message>"