name: JadedChat
version: '${project.version}'
main: net.jadedmc.jadedchat.JadedChat
api-version: 1.19
depend: [ PlaceholderAPI ]
softdepend: [ DiscordSRV, LuckPerms ]
authors: [ JadedMC ]
description: Feature-Rich Chat Plugin Developed by JadedMC
website: http://www.jadedmc.net

commands:
  channel:
    description: Change the current channel being used.
    aliases: [chat,ch]
  jadedchat:
    description: Main command for JadedChat.
    aliases: [jc]
  message:
    description: Send a private message to a player.
    aliases: [msg,tell,whisper,w,pm,dm]
  reply:
    description: Reply to a private message.
    aliases: [r,respond]
  socialspy:
    description: Spy on private messages.
    aliases: [spy, ss]